ribbon.client.name: history

chat:
  ribbon:
    listOfServers: http://beolnix.com

message:
  ribbon:
    listOfServers: http://beolnix.com


history:
  ribbon:
    listOfServers: http://beolnix.com

security.basic.enabled: false
management.security.enabled: false